version: '3'
services:
  db:
    image: mongo
    deploy:
      replicas: 3
      placement:
        constraints: [ node.role == manager ]

  nginx:
    image: nginx
    deploy:
      replicas: 3
    ports:
      - "80:80"
    volumes:
      - "./default: /etc/nginx/sites-enabled/"  

  landpage:
    image: lami1a/land
    deploy:
      replicas: 3
    ports:
      - "2000:2000"
    environment:
      NODE_ENV: "production"
      mongoUri: "mongodb://db"
    