  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data:/data

  nginx:
    image: nginx
  ports:
    - "80:80"
  volumes:
    - ./default: /etc/nginx/  

  landpage:
    image: lami1a/land
    ports:
      - "2000:2000"
    environment:
      NODE_ENV: "production"
      mongoUri: "mongodb://db"
    